/**
 * Raptor21 — public client surface.
 *
 * Ships with the package, so these types are available without installing anything from npm.
 *
 * Everything here is installed by the bundle, which RaptorScripts/the tag helper places in <head> — before
 * any page module runs. That ordering is what lets these be declared as present rather than optional.
 */

/** Options for the charting library. */
type RaptorChartOptions = any;

interface RaptorChartHandle {
    /** Draws the options, replacing any previous chart on the element. */
    render(options: RaptorChartOptions): Promise<void>;

    /** Applies options to the live chart, drawing it if there is none. */
    update(options: RaptorChartOptions): Promise<void>;

    /** Reveals the server-rendered <Empty> slot. */
    empty(): Promise<void>;

    /** Reveals the server-rendered <Error> slot. */
    fail(): Promise<void>;

    /** Reveals the server-rendered <Loading> slot. */
    loading(): Promise<void>;
}

/** One point on a map. */
interface RaptorMapMarker {
    id?: string;
    lat: number;
    lng: number;

    /** Tooltip text. Set as text, never as HTML. */
    label?: string;

    /** The marker's role, which decides how prominently it is drawn. */
    kind?: 'hub' | 'origin' | 'point';

    /** Relative magnitude, scaled against the largest of the same kind on the map. */
    weight?: number;
    color?: string;
}

/** A connection between two points, drawn as a curve. */
interface RaptorMapArc {
    fromLat: number;
    fromLng: number;
    toLat: number;
    toLng: number;

    /** Relative magnitude, scaled against the heaviest arc on the map. */
    weight?: number;
    color?: string;

    /** Tooltip text. Set as text, never as HTML. */
    label?: string;
}

/**
 * A map: a basemap, some points, and the connections between them.
 *
 * Data only — nothing here is evaluated on the client, so a page carrying a map needs no `unsafe-eval`.
 * Tiles are fetched as images from the basemap's host, which a strict `img-src` must allow.
 */
interface RaptorMapData {
    basemap?: 'cartoPositron' | 'cartoDarkMatter' | 'openStreetMap';

    /** A tile URL template overriding `basemap`, for hosts running their own tile server. */
    tileUrl?: string;
    attribution?: string;

    centerLat?: number;
    centerLng?: number;
    zoom?: number;

    /** Frame the view on the data instead of a fixed centre and zoom. Defaults to true. */
    fitToData?: boolean;

    markers?: RaptorMapMarker[];
    arcs?: RaptorMapArc[];

    /** Whether scrolling over the map zooms it. Defaults to false, so the page keeps its scroll. */
    scrollWheelZoom?: boolean;
    zoomControl?: boolean;
}

interface RaptorMapHandle {
    /** Draws the model, replacing any previous map on the element. */
    render(data: RaptorMapData): Promise<void>;

    /** Redraws with a new model. */
    update(data: RaptorMapData): Promise<void>;

    /** Reveals the server-rendered <Empty> slot. */
    empty(): Promise<void>;

    /** Reveals the server-rendered <Error> slot. */
    fail(): Promise<void>;

    /** Reveals the server-rendered <Loading> slot. */
    loading(): Promise<void>;
}

interface RaptorGridApi {
    /** Row keys currently selected in a grid. */
    getSelection(gridId: string): string[];

    clearSelection(gridId: string): void;

    /** Reloads one grid's region, keeping its current page, sort and filters. */
    refresh(gridId: string): void;

    /** Reloads every grid inside `root` (the document by default). */
    refreshAll(root?: ParentNode): void;

    /**
     * The form carrying a grid's request state — page, sort, column order and every filter input.
     *
     * Use this instead of rebuilding the `<gridId>-form` id by hand: the id is generated by the region
     * component, so a hand-written copy breaks with no compile error.
     */
    form(gridId: string): HTMLFormElement | null;

    /**
     * The filter and sort state the grid would POST to its own endpoint right now — column filters, set
     * (checkbox) filters, and the conditions of every `hx-include`d filter panel.
     *
     * Reported in the library's own vocabulary — strings, not your API's enum numbers. Map it to whatever
     * your backend expects. Do not read the region's form yourself, and do not keep a column -> type table
     * of your own: the server already encoded the type in the filter input it rendered.
     */
    state(gridId: string): RaptorGridState;
}

interface RaptorGridFilterState {
    /** The column key, as the server derived it from the bound member expression. */
    column: string;

    /** What kind of value the column holds. */
    kind: 'text' | 'number' | 'date';

    /** The chosen comparison — "contains", "equals", "greaterThan", "in", "between", ... */
    operation: string;

    /** The raw value the user typed or picked. Empty for set filters — see `values`. */
    value: string;

    /** The range's second value, when the operation is a between. */
    valueTo?: string;

    /** The selections of a set (multi-value) filter. */
    values?: string[];
}

interface RaptorGridState {
    filters: RaptorGridFilterState[];
    sort: { column: string; direction: 'asc' | 'desc' } | null;

    /** An included filter panel's free-text search, when one is set. */
    search: string | null;
}

/**
 * One step reported by a running operation, in the library's vocabulary — map your stream's own frames
 * onto these. The dialog never learns a consumer's wire format, the same way raptorGrid.state() reports
 * filters in this library's words.
 */
type RaptorProgressFrame =
/** How much work there is. Honoured once — the first positive total is the one reported. */
    | { kind: 'total'; total: number }
    /**
     * Work done. `processed` is absolute and wins over the relative `advance` when both are present;
     * `total` refreshes the denominator without rewriting the "total rows" line.
     */
    | { kind: 'progress'; processed?: number; advance?: number; total?: number }
    /** A non-fatal problem. Accumulates in a warning box; the operation keeps running. */
    | { kind: 'warning'; message: string }
    /** A problem the producer kept streaming through. Shown; the dialog keeps consuming. */
    | { kind: 'error'; message: string }
    /** The operation finished, optionally with a file to hand back. */
    | {
    kind: 'done';
    processed?: number;
    downloadUrl?: string | null;
    /**
     * Whether a file was produced at all, when that differs from "did I get a URL" — a producer that
     * identified a file but could not build a URL for it sets this true so the dialog does not end on
     * its "finished, nothing to download" line. Defaults to `downloadUrl !== null`.
     */
    hasFile?: boolean;
}

/** Every string the dialog renders. Override field by field; anything omitted keeps the default. */
interface RaptorProgressText {
    preparing: string;

    /** `total` is null while the size of the job is unknown. Both numbers arrive pre-formatted. */
    processing: (processed: string, total: string | null) => string;

    completed: (processed: string) => string;

    totalRows: (total: string) => string;

    /** Time left, once estimable. `remaining` arrives pre-humanised ("2m 15s"). */
    eta: (remaining: string) => string;

    /** Shown in the ETA's place while the rate is still too noisy to project from. */
    etaCalculating: string;

    errorTitle: string;

    completedNoFile: string;

    unexpected: string;
}

interface RaptorProgressOptions {
    title?: string;

    /**
     * Opens the operation and yields its frames. A factory, not an iterable: nothing starts until the
     * dialog is on screen, so the request is never in flight before the user has something to look at.
     */
    stream: () => AsyncIterable<RaptorProgressFrame>;

    text?: Partial<RaptorProgressText>;

    /** Delay before the dialog closes itself once the operation completes. 0 keeps it open. Default 800. */
    autoCloseMs?: number;

    /** Trigger the `done` frame's downloadUrl. Default true. */
    download?: boolean;
}

interface RaptorProgressResult {
    completed: boolean;
    processed: number;
    downloadUrl: string | null;
    error: string | null;
}

interface RaptorProgressApi {
    /**
     * Opens a modal that reports a long-running operation, resolving when its stream ends.
     *
     * Errors are shown IN the dialog and reported through the result's `error` rather than thrown: a
     * failed operation must leave the user looking at a dialog that says so.
     */
    run(options: RaptorProgressOptions): Promise<RaptorProgressResult>;
}

type RaptorNotifyType = 'success' | 'error' | 'warning' | 'info';

interface RaptorNotifyOptions {
    /** Optional bold heading shown above the message. */
    title?: string;

    /** Main message body. */
    message: string;

    /**
     * Rendered as a scrollable, copyable block under the message — the ids an import skipped, say.
     * Its presence also makes the toast sticky by default.
     */
    items?: string[];

    type?: RaptorNotifyType;

    /** Auto-dismiss delay in ms. 0 keeps the toast until the user closes it. */
    duration?: number;
}

interface RaptorConfirmOptions {
    title?: string;
    message: string;
    confirmText?: string;
    cancelText?: string;

    /** Visual emphasis of the confirm button. */
    type?: 'default' | 'warning' | 'danger';
}

interface RaptorNotifyApi {
    success(message: string, options?: Partial<RaptorNotifyOptions>): void;

    error(message: string, options?: Partial<RaptorNotifyOptions>): void;

    warning(message: string, options?: Partial<RaptorNotifyOptions>): void;

    info(message: string, options?: Partial<RaptorNotifyOptions>): void;

    show(options: RaptorNotifyOptions): void;

    /**
     * A confirmation resolving true (confirm) or false (cancel / backdrop / Escape).
     *
     * Not the dialog `hx-confirm` opens — that one is a real `.rg-modal`. This is built imperatively and
     * renders above an already-open modal.
     */
    confirm(options: RaptorConfirmOptions): Promise<boolean>;
}

interface Window {
    /**
     * A handle for a chart element, by id or element.
     *
     * Resolves the element on every call rather than capturing it: a swap replaces the node, and a handle
     * held across one would otherwise draw into a detached element.
     */
    raptorChart: (target: string | HTMLElement) => RaptorChartHandle;

    /**
     * A handle for a map element, by id or element.
     *
     * Resolves the element on every call, for the same reason as the chart handle above.
     */
    raptorMap: (target: string | HTMLElement) => RaptorMapHandle;

    /** Grid operations, by grid id. */
    raptorGrid: RaptorGridApi;

    /** Shorthand for `raptorGrid.refresh`. */
    raptorGridRefresh: (gridId: string) => void;

    /** The streaming progress dialog. */
    raptorProgress: RaptorProgressApi;

    /** Toast notifications and the imperative, modal-independent confirm. */
    raptorNotify: RaptorNotifyApi;

    /** True once the bundle has installed its APIs. */
    raptorReady?: boolean;
}
