import {clearSelection, peekSelection} from './selection-store'

/**
 * The public window API.
 *
 * Installed eagerly from the entry bundle rather than from a component's lazily-imported chunk, so it is
 * callable at arbitrary times — right after a create or update completes, for instance — including
 * before the grid chunk resolves and on pages where no grid mounted.
 */

interface RaptorGridApi {
    getSelection(gridId: string): string[]

    clearSelection(gridId: string): void

    /** Reloads one grid's region, keeping its current page, sort and filters. */
    refresh(gridId: string): void

    /**
     * Reloads every grid inside `root` (the document by default). Locates them through the region's own
     * markup conventions, so callers need not know the internal class names.
     */
    refreshAll(root?: ParentNode): void

    /**
     * The form carrying a grid's request state — page, sort, column order and every filter input.
     *
     * The ids it is found by (`<gridId>-form`, `<gridId>-region`) are generated by the region component,
     * so resolving the form is published here rather than left to callers rebuilding those strings.
     */
    form(gridId: string): HTMLFormElement | null

    /**
     * What the user has currently filtered and sorted a grid by.
     *
     * Reads the region's form so callers need not know the `f_` / `fop_` / `sort` / `dir` field-name
     * prefixes, nor keep their own map of column to data type — the server already encodes the type in
     * each filter input's `type` attribute.
     *
     * Reported in this library's own vocabulary: strings, not the numeric enums of any consuming API. A
     * caller maps these onto whatever its backend expects.
     */
    state(gridId: string): RaptorGridState
}

/** A single active filter, in the library's vocabulary. */
interface RaptorGridFilterState {
    /** The column key, as the server derived it from the bound member expression. */
    column: string

    /** What kind of value the column holds, taken from the filter input the server rendered. */
    kind: 'text' | 'number' | 'date'

    /** The chosen comparison. Names match GridFilterOperation. */
    operation: string

    /** The raw value the user typed or picked. */
    value: string
}

interface RaptorGridState {
    filters: RaptorGridFilterState[]
    sort: { column: string; direction: 'asc' | 'desc' } | null
}

declare global {
    interface Window {
        raptorGrid?: RaptorGridApi
        raptorGridRefresh?: (gridId: string) => void
    }
}

/**
 * Reloads a grid's region. Fires the form's custom `raptor:refresh` htmx trigger, which re-POSTs the
 * current filter/sort/page state and swaps the region. A no-op when the grid is not on the page, so a
 * screen can call it unconditionally after a mutation.
 */
export function refreshGrid(gridId: string): void {
    const form = gridForm(gridId)
    if (form) window.htmx?.trigger(form, 'raptor:refresh')
}

/** The id the region component gives a grid's state form. The one place this string is built. */
export function gridForm(gridId: string): HTMLFormElement | null {
    const form = document.getElementById(`${gridId}-form`)
    return form instanceof HTMLFormElement ? form : null
}

/**
 * Reads a grid's current filter and sort state off the form the region renders.
 *
 * The type of each filter comes from the input the server emitted (`type="number"`, `"date"`, otherwise
 * text), which the server derived from the column's GridFilterType when it rendered the popup.
 *
 * Set filters (`fs_` checkbox groups) are not reported: they are a multi-value shape that does not fit
 * the single-`value` model here.
 */
export function gridState(gridId: string): RaptorGridState {
    const form = gridForm(gridId)
    if (!form) return {filters: [], sort: null}

    const data = new FormData(form)
    const filters: RaptorGridFilterState[] = []

    for (const control of form.querySelectorAll<HTMLInputElement>('input[name^="f_"]')) {
        const column = control.name.slice(2)
        const value = (data.get(control.name)?.toString() ?? '').trim()
        if (!value) continue

        const kind = control.type === 'number' ? 'number' : control.type === 'date' ? 'date' : 'text'
        const operation = data.get(`fop_${column}`)?.toString()
            || (kind === 'text' ? 'contains' : 'equals')

        filters.push({column, kind, operation, value})
    }

    const sortColumn = data.get('sort')?.toString()
    const sort = sortColumn
        ? {column: sortColumn, direction: data.get('dir') === 'desc' ? 'desc' as const : 'asc' as const}
        : null

    return {filters, sort}
}

/**
 * Reloads every grid under `root`.
 *
 * Useful after a cached page is painted back from a snapshot: the markup is whatever was on screen when
 * it was captured, so each grid re-requests its own current state in the background.
 */
export function refreshGridsIn(root: ParentNode = document): void {
    root.querySelectorAll<HTMLFormElement>('form.rg-form')
        .forEach(form => window.htmx?.trigger(form, 'raptor:refresh'))
}

/**
 * Publishes `window.raptorGrid` and subscribes to server-driven refreshes.
 *
 * A handler answering with `HX-Trigger: {"raptor:grid-refresh":"<gridId>"}` reloads that grid through its
 * own form, preserving the page, sort and filters currently on screen. The grid id is accepted both as a
 * bare string and wrapped as `{ value, elt }`, which is how htmx 2.x dispatches a scalar trigger value.
 */
export function installApi(): void {
    window.raptorGridRefresh = refreshGrid

    document.body.addEventListener('raptor:grid-refresh', event => {
        const detail = (event as CustomEvent<unknown>).detail
        const gridId = typeof detail === 'string'
            ? detail
            : typeof (detail as { value?: unknown } | null)?.value === 'string'
                ? (detail as { value: string }).value
                : null
        if (gridId) refreshGrid(gridId)
    })

    const api = (window.raptorGrid ??= {} as RaptorGridApi)
    api.getSelection = (gridId: string): string[] => [...peekSelection(gridId)]
    api.clearSelection = clearSelection
    api.refresh = refreshGrid
    api.refreshAll = refreshGridsIn
    api.form = gridForm
    api.state = gridState
}
